In [1]:
import torch
from torch import nn
import torch.nn.functional as F
import torchvision
import urllib
from PIL import Image
import matplotlib.pyplot as plt
from torchvision import transforms
import numpy as np

In [27]:
m = nn.Conv2d(3, 6, kernel_size=3, stride=1, padding=1)
input = torch.randn(3, 5, 5).unsqueeze(0)
output = m(input)

In [4]:
m = nn.Conv3d(1, 6, kernel_size=(3,3,3), stride=1, padding = (1, 1, 1))
# non-square kernels and unequal stride and with padding
# m = nn.Conv3d(16, 33, (1, 3, 3), stride=(2, 1, 1), padding=(4, 2, 0))
input = torch.randn(1, 3, 5, 5).unsqueeze(0)
output = m(input)

In [45]:
m = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
input = torch.zeros(5, 5)
for i in range(5):
    for j in range(5):
        input[i, j] = 100 - ((i + 1) * (j + 1) * 5)
input = F.pad(input, (2, 2, 2, 2))
input = input.unsqueeze(0)
output = m(input)

In [22]:
m = nn.MaxPool3d(kernel_size=(1, 2, 2), stride=(1, 2, 2))
input = torch.zeros(3, 11, 11)
for i in range(3):
    for j in range(11):
        for k in range(11):
            if i == 0:
                input[i, j, k] = 1
            if i == 1:
                input[i, j, k] = 2
            if i == 2:
                input[i, j, k] = 3
                
input = input.unsqueeze(0).unsqueeze(0)
output = m(input)
asd = m(output)
asd1 = m(asd)

In [5]:
print(input.shape)
print(output.shape)
# print(asd1.shape)
# print(output.unsqueeze(3).shape)

torch.Size([1, 1, 3, 5, 5])
torch.Size([1, 6, 3, 5, 5])


In [19]:
input

tensor([[[[[ 1.0602,  1.8160,  0.2813,  1.0162, -0.5871],
           [-0.6760, -0.4380,  0.1310,  1.7514,  1.0639],
           [-2.0667,  0.2343, -1.5016,  0.6920, -0.6425],
           [ 1.0677,  0.7157, -0.2001,  0.9387,  0.8589],
           [-0.5681,  0.6441, -2.3842,  0.4579,  0.1049]],

          [[ 1.2174,  0.0341,  1.5246,  0.6730, -1.2210],
           [ 1.4757, -0.4945, -0.4488, -1.1446, -0.5758],
           [-0.6861, -1.4668,  0.6706,  0.9712, -0.5399],
           [-0.6505, -0.4348, -0.0951, -0.0409, -0.1782],
           [ 0.2637,  0.7003,  1.3759,  1.4506,  1.1615]],

          [[-0.2473,  1.1174, -0.3417, -0.4446, -0.3672],
           [-1.6260,  0.4808, -0.8401, -1.2263,  1.2366],
           [ 0.6179,  0.1336, -0.2789,  1.1625,  1.3546],
           [ 0.2970, -0.5224,  0.6980,  1.7401, -0.1446],
           [ 0.7441,  0.2460, -0.2689,  0.7367, -0.2709]]]]])

In [20]:
output

tensor([[[[[-1.0051e+00, -8.8651e-01, -7.1676e-02,  5.5849e-02,  3.6465e-01],
           [-5.4894e-01, -1.1965e+00, -5.6947e-01, -1.1878e+00, -3.3092e-01],
           [ 4.2785e-01,  5.4881e-02, -1.3371e-01, -2.3685e-01,  3.1782e-01],
           [-6.8492e-01, -1.0030e+00, -4.9581e-01, -1.1198e+00, -3.4979e-01],
           [-4.2433e-01,  1.4422e-01, -1.4385e-01, -6.1185e-01, -2.0411e-01]],

          [[-6.5545e-01, -3.1654e-01, -1.2677e+00, -5.9636e-01, -4.0989e-01],
           [-9.4900e-01, -5.2848e-01, -1.6470e-01,  5.7070e-01,  3.8231e-03],
           [ 1.6749e-01, -1.8732e-01, -4.9043e-01, -4.4486e-01, -3.2444e-01],
           [ 5.1024e-01,  8.6202e-03,  1.4505e-01,  8.4261e-01,  2.1090e-01],
           [-4.0475e-01, -7.2617e-01, -8.5026e-01, -7.4972e-01, -5.5126e-01]],

          [[-3.6097e-01, -1.1952e+00, -4.6073e-01, -4.2238e-02, -5.2974e-01],
           [-3.2881e-01, -5.0601e-03,  6.5041e-01,  1.9613e-01, -2.2271e-01],
           [-8.7728e-01,  1.9255e-01,  3.2231e-01, -1.0440e+

In [232]:
asd1

tensor([[[[[1.]],

          [[2.]],

          [[3.]]]]])

In [233]:
asd1 = torch.squeeze(torch.squeeze(asd1, 0), 0)

In [234]:
asd1.shape

torch.Size([3, 1, 1])